export { default as Home } from './Home'
export { default as Allevents } from './Allevents'
export { default as Addevents } from './Addevents'
export { default as Deleteevents } from './Deleteevents'
export { default as AllTickets } from './AllTickets'
export { default as EventDetails } from './EventDetails'
export { default as NotFound } from './NotFound'