export { default as Home } from './Home'
export { default as About } from './About'
export { default as Event } from './Event'
export { default as UpcomingEvents } from './UpcomingEvents'
export { default as NotFound } from './NotFound'